sudo: false
dist: trusty
language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
install:
  - pip install --upgrade pip
  - pip install -r testing_requirements.txt
script:
  - python setup.py install
  - coverage run --source=dc_base_scrapers ./run_tests.py
after_success:
  - coveralls
